// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiteDiscover.Persistence.Contexts.EntityFramework;

#nullable disable

namespace SiteDiscover.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240722194849_add network arch image")]
    partial class addnetworkarchimage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SiteDiscover.Domain.Entities.DigitalSignage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Cloud")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SiteId")
                        .IsUnique();

                    b.ToTable("DigitalSignages");
                });

            modelBuilder.Entity("SiteDiscover.Domain.Entities.GeneralInformation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LaunchYear")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfEmployees")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatingHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SiteSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SiteId")
                        .IsUnique();

                    b.ToTable("GeneralInformations");
                });

            modelBuilder.Entity("SiteDiscover.Domain.Entities.ITContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ITContactCategory")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserJobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("ITContacts");
                });

            modelBuilder.Entity("SiteDiscover.Domain.Entities.ITContactUploadedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ITContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UploadedFileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ITContactId")
                        .IsUnique();

                    b.HasIndex("UploadedFileId")
                        .IsUnique();

                    b.ToTable("ITContactUploadedFiles");
                });

            modelBuilder.Entity("SiteDiscover.Domain.Entities.MeetingRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfStandardMeetingRooms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TotalMeetingRooms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SiteId")
                        .IsUnique();

                    b.ToTable("MeetingRooms");
                });

            modelBuilder.Entity("SiteDiscover.Domain.Entities.NetworkArchitecture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConnectionSpeed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfInternetLines")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SiteId")
                        .IsUnique();

                    b.ToTable("NetworkArchitectures");
                });

            modelBuilder.Entity("SiteDiscover.Domain.Entities.NetworkArchitectureUploadedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NetworkArchitectureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UploadedFileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NetworkArchitectureId");

                    b.HasIndex("UploadedFileId")
                        .IsUnique();

                    b.ToTable("NetworkArchitectureUploadedFiles");
                });

            modelBuilder.Entity("SiteDiscover.Domain.Entities.ServerRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfServerRooms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TotalMeetingRooms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SiteId")
                        .IsUnique();

                    b.ToTable("ServerRooms");
                });

            modelBuilder.Entity("SiteDiscover.Domain.Entities.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryISO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LocalTeam")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("SiteDiscover.Domain.Entities.UploadedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Directory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FileType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UploadedFiles");
                });

            modelBuilder.Entity("SiteDiscover.Domain.Entities.DigitalSignage", b =>
                {
                    b.HasOne("SiteDiscover.Domain.Entities.Site", "Site")
                        .WithOne("DigitalSignage")
                        .HasForeignKey("SiteDiscover.Domain.Entities.DigitalSignage", "SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("SiteDiscover.Domain.Entities.GeneralInformation", b =>
                {
                    b.HasOne("SiteDiscover.Domain.Entities.Site", "Site")
                        .WithOne("GeneralInformation")
                        .HasForeignKey("SiteDiscover.Domain.Entities.GeneralInformation", "SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("SiteDiscover.Domain.Entities.ITContact", b =>
                {
                    b.HasOne("SiteDiscover.Domain.Entities.Site", "Site")
                        .WithMany("Contacts")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("SiteDiscover.Domain.Entities.ITContactUploadedFile", b =>
                {
                    b.HasOne("SiteDiscover.Domain.Entities.ITContact", "ITContact")
                        .WithOne("ITContactUploadedFile")
                        .HasForeignKey("SiteDiscover.Domain.Entities.ITContactUploadedFile", "ITContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiteDiscover.Domain.Entities.UploadedFile", "UploadedFile")
                        .WithOne("ITContactUploadedFile")
                        .HasForeignKey("SiteDiscover.Domain.Entities.ITContactUploadedFile", "UploadedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ITContact");

                    b.Navigation("UploadedFile");
                });

            modelBuilder.Entity("SiteDiscover.Domain.Entities.MeetingRoom", b =>
                {
                    b.HasOne("SiteDiscover.Domain.Entities.Site", "Site")
                        .WithOne("MeetingRoom")
                        .HasForeignKey("SiteDiscover.Domain.Entities.MeetingRoom", "SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("SiteDiscover.Domain.Entities.NetworkArchitecture", b =>
                {
                    b.HasOne("SiteDiscover.Domain.Entities.Site", "Site")
                        .WithOne("NetworkArchitecture")
                        .HasForeignKey("SiteDiscover.Domain.Entities.NetworkArchitecture", "SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("SiteDiscover.Domain.Entities.NetworkArchitectureUploadedFile", b =>
                {
                    b.HasOne("SiteDiscover.Domain.Entities.NetworkArchitecture", "NetworkArchitecture")
                        .WithMany()
                        .HasForeignKey("NetworkArchitectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiteDiscover.Domain.Entities.UploadedFile", "UploadedFile")
                        .WithOne("NetworkArchitectureUploadedFile")
                        .HasForeignKey("SiteDiscover.Domain.Entities.NetworkArchitectureUploadedFile", "UploadedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NetworkArchitecture");

                    b.Navigation("UploadedFile");
                });

            modelBuilder.Entity("SiteDiscover.Domain.Entities.ServerRoom", b =>
                {
                    b.HasOne("SiteDiscover.Domain.Entities.Site", "Site")
                        .WithOne("ServerRoom")
                        .HasForeignKey("SiteDiscover.Domain.Entities.ServerRoom", "SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("SiteDiscover.Domain.Entities.ITContact", b =>
                {
                    b.Navigation("ITContactUploadedFile")
                        .IsRequired();
                });

            modelBuilder.Entity("SiteDiscover.Domain.Entities.Site", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("DigitalSignage")
                        .IsRequired();

                    b.Navigation("GeneralInformation")
                        .IsRequired();

                    b.Navigation("MeetingRoom")
                        .IsRequired();

                    b.Navigation("NetworkArchitecture")
                        .IsRequired();

                    b.Navigation("ServerRoom")
                        .IsRequired();
                });

            modelBuilder.Entity("SiteDiscover.Domain.Entities.UploadedFile", b =>
                {
                    b.Navigation("ITContactUploadedFile")
                        .IsRequired();

                    b.Navigation("NetworkArchitectureUploadedFile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
