//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDiscover.Presentation.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_tr_TR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_tr_TR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiteDiscover.Presentation.Resources.Views.Home.Index.tr-TR", typeof(Index_tr_TR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu site, iştiraklerin ve sitelerin altyapısı hakkında kısa bilgi depolamayı amaçlamaktadır. Keşfetmek mi istiyorsunuz? Hadi buradan başlayalım!.
        /// </summary>
        internal static string main_article {
            get {
                return ResourceManager.GetString("main-article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitelerin Bilgi Veritabanı.
        /// </summary>
        internal static string main_title {
            get {
                return ResourceManager.GetString("main-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İştirakleri ve Siteleri Görmek İçin Ülkelere Tıklayın!.
        /// </summary>
        internal static string map_title {
            get {
                return ResourceManager.GetString("map-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hızlı Bağlantılar.
        /// </summary>
        internal static string quick_links {
            get {
                return ResourceManager.GetString("quick-links", resourceCulture);
            }
        }
    }
}
